spring.application.name=odontologiabff

server.port=8080


# Microservicio Turno
ms.turno.url=http://localhost:8084/turno
ms.facturacion.url=http://localhost:8086/facturacion

# Microservicio Paciente
ms.paciente.url=http://localhost:8081/paciente

# Microservicio Odontologo
ms.odontologo.url=http://localhost:8082/odontologo

ms.tratamientos.url=http://localhost:8087/tratamientos

ms.historialclinico.url=http://localhost:8086/historialclinico

ms.usuario.url=http://localhost:8085

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packagesToScan=com.proyecto.odontologiabff.controller
spring.jackson.serialization.write-dates-as-timestamps=false

# springdoc.packagesToScan=com.example.demo.controller ejemplo

secret=hT+9vN2h8wZs3ZEDZjB9Shu34f1dGr2bUjDcz3cEhR4=
spring.main.allow-bean-definition-overriding=true


# Microservicio Diente
ms.diente.url=http://localhost:8090/api/dientes


# propiedades del mail 


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dentalhub.organization@gmail.com
spring.mail.password=qvihzgrpehmhqjau
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=
